import constants from '../constants';

export function createEvent(eventInterface: 'AnimationEvent'): AnimationEvent;
export function createEvent(eventInterface: 'AnimationPlaybackEvent'): AnimationPlaybackEvent;
export function createEvent(eventInterface: 'AudioProcessingEvent'): AudioProcessingEvent;
export function createEvent(eventInterface: 'BeforeUnloadEvent'): BeforeUnloadEvent;
export function createEvent(eventInterface: 'ClipboardEvent'): ClipboardEvent;
export function createEvent(eventInterface: 'CloseEvent'): CloseEvent;
export function createEvent(eventInterface: 'CompositionEvent'): CompositionEvent;
export function createEvent(eventInterface: 'CustomEvent'): CustomEvent;
export function createEvent(eventInterface: 'DeviceLightEvent'): DeviceLightEvent;
export function createEvent(eventInterface: 'DeviceMotionEvent'): DeviceMotionEvent;
export function createEvent(eventInterface: 'DeviceOrientationEvent'): DeviceOrientationEvent;
export function createEvent(eventInterface: 'DragEvent'): DragEvent;
export function createEvent(eventInterface: 'ErrorEvent'): ErrorEvent;
export function createEvent(eventInterface: 'Event'): Event;
export function createEvent(eventInterface: 'Events'): Event;
export function createEvent(eventInterface: 'FocusEvent'): FocusEvent;
export function createEvent(eventInterface: 'FocusNavigationEvent'): FocusNavigationEvent;
export function createEvent(eventInterface: 'GamepadEvent'): GamepadEvent;
export function createEvent(eventInterface: 'HashChangeEvent'): HashChangeEvent;
export function createEvent(eventInterface: 'IDBVersionChangeEvent'): IDBVersionChangeEvent;
export function createEvent(eventInterface: 'KeyboardEvent'): KeyboardEvent;
export function createEvent(eventInterface: 'ListeningStateChangedEvent'): ListeningStateChangedEvent;
export function createEvent(eventInterface: 'MSGestureEvent'): MSGestureEvent;
export function createEvent(eventInterface: 'MSMediaKeyMessageEvent'): MSMediaKeyMessageEvent;
export function createEvent(eventInterface: 'MSMediaKeyNeededEvent'): MSMediaKeyNeededEvent;
export function createEvent(eventInterface: 'MSPointerEvent'): MSPointerEvent;
export function createEvent(eventInterface: 'MediaEncryptedEvent'): MediaEncryptedEvent;
export function createEvent(eventInterface: 'MediaKeyMessageEvent'): MediaKeyMessageEvent;
export function createEvent(eventInterface: 'MediaQueryListEvent'): MediaQueryListEvent;
export function createEvent(eventInterface: 'MediaStreamErrorEvent'): MediaStreamErrorEvent;
export function createEvent(eventInterface: 'MediaStreamEvent'): MediaStreamEvent;
export function createEvent(eventInterface: 'MediaStreamTrackEvent'): MediaStreamTrackEvent;
export function createEvent(eventInterface: 'MessageEvent'): MessageEvent;
export function createEvent(eventInterface: 'MouseEvent'): MouseEvent;
export function createEvent(eventInterface: 'MouseEvents'): MouseEvent;
export function createEvent(eventInterface: 'MutationEvent'): MutationEvent;
export function createEvent(eventInterface: 'MutationEvents'): MutationEvent;
export function createEvent(eventInterface: 'OfflineAudioCompletionEvent'): OfflineAudioCompletionEvent;
export function createEvent(eventInterface: 'OverflowEvent'): OverflowEvent;
export function createEvent(eventInterface: 'PageTransitionEvent'): PageTransitionEvent;
export function createEvent(eventInterface: 'PaymentRequestUpdateEvent'): PaymentRequestUpdateEvent;
export function createEvent(eventInterface: 'PermissionRequestedEvent'): PermissionRequestedEvent;
export function createEvent(eventInterface: 'PointerEvent'): PointerEvent;
export function createEvent(eventInterface: 'PopStateEvent'): PopStateEvent;
export function createEvent(eventInterface: 'ProgressEvent'): ProgressEvent;
export function createEvent(eventInterface: 'PromiseRejectionEvent'): PromiseRejectionEvent;
export function createEvent(eventInterface: 'RTCDTMFToneChangeEvent'): RTCDTMFToneChangeEvent;
export function createEvent(eventInterface: 'RTCDataChannelEvent'): RTCDataChannelEvent;
export function createEvent(eventInterface: 'RTCDtlsTransportStateChangedEvent'): RTCDtlsTransportStateChangedEvent;
export function createEvent(eventInterface: 'RTCErrorEvent'): RTCErrorEvent;
export function createEvent(eventInterface: 'RTCIceCandidatePairChangedEvent'): RTCIceCandidatePairChangedEvent;
export function createEvent(eventInterface: 'RTCIceGathererEvent'): RTCIceGathererEvent;
export function createEvent(eventInterface: 'RTCIceTransportStateChangedEvent'): RTCIceTransportStateChangedEvent;
export function createEvent(eventInterface: 'RTCPeerConnectionIceErrorEvent'): RTCPeerConnectionIceErrorEvent;
export function createEvent(eventInterface: 'RTCPeerConnectionIceEvent'): RTCPeerConnectionIceEvent;
export function createEvent(eventInterface: 'RTCSsrcConflictEvent'): RTCSsrcConflictEvent;
export function createEvent(eventInterface: 'RTCStatsEvent'): RTCStatsEvent;
export function createEvent(eventInterface: 'RTCTrackEvent'): RTCTrackEvent;
export function createEvent(eventInterface: 'SVGZoomEvent'): SVGZoomEvent;
export function createEvent(eventInterface: 'SVGZoomEvents'): SVGZoomEvent;
export function createEvent(eventInterface: 'SecurityPolicyViolationEvent'): SecurityPolicyViolationEvent;
export function createEvent(eventInterface: 'ServiceWorkerMessageEvent'): ServiceWorkerMessageEvent;
export function createEvent(eventInterface: 'SpeechRecognitionError'): SpeechRecognitionError;
export function createEvent(eventInterface: 'SpeechRecognitionEvent'): SpeechRecognitionEvent;
export function createEvent(eventInterface: 'SpeechSynthesisErrorEvent'): SpeechSynthesisErrorEvent;
export function createEvent(eventInterface: 'SpeechSynthesisEvent'): SpeechSynthesisEvent;
export function createEvent(eventInterface: 'StorageEvent'): StorageEvent;
export function createEvent(eventInterface: 'TextEvent'): TextEvent;
export function createEvent(eventInterface: 'TouchEvent'): TouchEvent;
export function createEvent(eventInterface: 'TrackEvent'): TrackEvent;
export function createEvent(eventInterface: 'TransitionEvent'): TransitionEvent;
export function createEvent(eventInterface: 'UIEvent'): UIEvent;
export function createEvent(eventInterface: 'UIEvents'): UIEvent;
export function createEvent(eventInterface: 'VRDisplayEvent'): VRDisplayEvent;
export function createEvent(eventInterface: 'VRDisplayEvent '): VRDisplayEvent;
export function createEvent(eventInterface: 'WebGLContextEvent'): WebGLContextEvent;
export function createEvent(eventInterface: 'WheelEvent'): WheelEvent;
export function createEvent(eventInterface: string): Event;
export function createEvent(eventInterface: string): Event {
    const event = constants.document.createEvent(eventInterface);

    return event;
}
